export const formControlClassName = [
  "w-full",
  "rounded-md",
  "border border-input",
  "bg-background text-foreground",
  "shadow-sm",
  "transition-colors",
  "placeholder:text-muted-foreground",
  "focus-visible:outline-none",
  "focus-visible:ring-2",
  "focus-visible:ring-ring",
  "focus-visible:ring-offset-2",
  "focus-visible:ring-offset-background",
  "disabled:cursor-not-allowed",
  "disabled:opacity-50",
].join(" ");